// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BetterUserSecrets
{
    internal sealed partial class Vsix
    {
        public const string Id = "BetterUserSecrets.d7496248-7dc7-4b20-b697-d4965920f227";
        public const string Name = "Better User Secrets";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Calvin A. Allen";
        public const string Tags = "";
    }
}
