// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.BetterUserSecrets
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS-BetterUserSecrets";
        public const string Name = "Better User Secrets";
        public const string Description = @"This extension adds a right-click context menu command that allows you to open manage your local user secrets for any project type - not just Web projects, which is the default Visual Studio behavior.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Coding With Calvin";
        public const string Tags = "secrets, user-secrets";
    }
}
