// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.BetterUserSecrets
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "715d713d-7df8-47d8-b8df-9ac1501914e2";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidBUSCmdSetString = "23234085-9ecc-48a5-99f2-8addb95dab56";
        public static Guid guidBUSCmdSet = new Guid(guidBUSCmdSetString);

        public const string guidIconsString = "6377c0b9-91ee-43f7-ba31-78df9ffe78cf";
        public static Guid guidIcons = new Guid(guidIconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int BUSId = 0x0100;
        public const int BUSIcon = 0x0001;
    }
}